"""Fix typo in interview_summery column

Revision ID: 10cbb29f2a8b
Revises: a2cf6205d3d5
Create Date: 2025-05-26 14:30:04.552207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cbb29f2a8b'
down_revision: Union[str, None] = 'a2cf6205d3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('interview_summery', sa.String(), nullable=True))
    op.drop_column('job_applications', 'interview_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('interview_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('job_applications', 'interview_summery')
    # ### end Alembic commands ###
