"""Add interview_summary to job_applications

Revision ID: a2cf6205d3d5
Revises: 
Create Date: 2025-05-25 16:17:03.514508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cf6205d3d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('job_applications', sa.Column('interview_summary', sa.String(), nullable=True))
    op.add_column('job_applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('job_applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('job_applications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_applications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'user_id')
    op.drop_column('job_applications', 'updated_at')
    op.drop_column('job_applications', 'created_at')
    op.drop_column('job_applications', 'interview_summary')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
